"""empty message

Revision ID: 49f5d593a5e5
Revises: 
Create Date: 2025-03-16 14:23:42.148807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f5d593a5e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('currency_rate')
    # Rimuovi la chiave esterna prima di eliminare la tabella
    with op.batch_alter_table('quote') as batch_op:
        batch_op.drop_constraint('quote_ibfk_2', type_='foreignkey')
    op.drop_table('material')
    op.drop_table('quote')
    op.drop_table('production_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('last_password_reset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_password_reset', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    op.create_table('production_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('setup_cost', mysql.FLOAT(), nullable=False),
    sa.Column('cutting_cost', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quote',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('production_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_cost', mysql.FLOAT(), nullable=False),
    sa.Column('total_cost', mysql.FLOAT(), nullable=False),
    sa.Column('currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('expiration_date', sa.DATE(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name='quote_ibfk_2'),
    sa.ForeignKeyConstraint(['production_type_id'], ['production_type.id'], name='quote_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='quote_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('material',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('thickness', mysql.FLOAT(), nullable=False),
    sa.Column('cost', mysql.FLOAT(), nullable=False),
    sa.Column('width', mysql.FLOAT(), nullable=False),
    sa.Column('height', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('currency_rate',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('target_currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
